### ISSUE TITLE
[QA] 태블릿 모드 노출 오류

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#102]
![스크린샷 2023-09-03 오후 10 49 27](https://github.com/brave-people/Dev-Event-Web/assets/28642484/1cb5982b-ab88-40da-850d-dfec929cc489)
> figma 
------
![스크린샷 2023-09-03 오후 10 50 03](https://github.com/brave-people/Dev-Event-Web/assets/28642484/0b2bec41-5281-4d80-b4a7-1c210154e3e4)
>  현재: 가로 2개의 행사가 보여야하는데 그렇지 않음

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
