### ISSUE TITLE
[QA] 반응형 개선 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#103]
![스크린샷 2023-09-03 오후 10 52 07](https://github.com/brave-people/Dev-Event-Web/assets/28642484/46ee0996-984d-443c-91fd-d7e6795d78f7)
> 리얼의 반응형: 과하게 축소하면 화면이 축소되서 보임 (실제 사용해보면 좋을듯!)
-------------
![스크린샷 2023-09-03 오후 10 51 53](https://github.com/brave-people/Dev-Event-Web/assets/28642484/413762c9-d01f-4506-ad38-74225ea66985)
> 재훈의 결과물: 과하게 축소하면 글씨가 위치를 벗어나있음. 

최소길이 설정한다음에 넘어가면 하단에 스크롤이 생기는 방법도 있긴한데, 현재 리얼에서 반응형대로 개발하는게 좋은것 같아!
리얼에서 반응형 써보고 너무 과하게 세로 길이가 줄어들면 화면이 축소되는 형식으로 작업되었으면 좋겠어!

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
수정할 여지가 많아 보이네..! 이슈 새로 열께!
