### ISSUE TITLE
[QA] 날짜 선택시 캘린더창이 사라짐 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#104]
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/f6d23c4d-b422-4ac9-98c6-885a93662436)
> 년도 변경 화살표 클릭시 캘린더창이 사라져!

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료
