### ISSUE TITLE
[QA] 개발자 도구 버그 수정

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#105]
![스크린샷 2023-09-03 오후 10 57 54](https://github.com/brave-people/Dev-Event-Web/assets/28642484/c317c9c8-6092-4146-a2dd-4aa12321d85a)
> 개발자 도구창에 오류가 계속 찍히네!

**Comment by Resister-boy** [comment]
첫 번째 경고는 Next.js에서 지원하는 Link 컴포넌트가 인자로 받는 path의 경로가 올바르지 않아서 생기는 경고입니다! 프론트에서 url 형식을 검사하는 방법으로 해결할 수 있기는 한데, 이벤트 등록할 때 제대로된 path를 넣어주면 되어서 지금까지 계속 무시하고 있었습니다! 

두 번째는 state끼리 순환참조를 하거나 컴포넌트가 마운트된 상태에서 페이지가 바뀌어버려서 메모리 누수가 발생하는데 이 부분은 수정했습니다!

**Comment by KoEonYack** [comment]
오키~!! 작업해주어서 고마워!!
