### ISSUE TITLE
[QA] 특정 사이즈에서 하단 배너 여백이 없음

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#106]
![스크린샷 2023-09-03 오후 10 59 06](https://github.com/brave-people/Dev-Event-Web/assets/28642484/919c45f5-5738-4483-bb78-460e4cec2137)
> 여기서 화면을 조금 줄이면 여백이 생기는데 스샷 정도의 사이즈에서는 하단 배너의 여백이 안보임!

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
