### ISSUE TITLE
[QA] 화면 크기가 줄어들었을때 다크모드/라이트모드 전환 버튼이 없음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#107]
![스크린샷 2023-09-03 오후 11 00 10](https://github.com/brave-people/Dev-Event-Web/assets/28642484/a969a194-1649-4a8b-b50c-9c4661083dee)
> 화면을 줄었을때 다크모드/라이트모드 전환 버튼이 없어!

**Comment by Resister-boy** [comment]
피그마에는 테블릿이랑 모바일 사이즈에서 테마 전환 버튼이 없는 것 같아서 안보이게 해놨습니다! 일단 이슈 반영해놓겠습니다!

**Comment by KoEonYack** [comment]
@Resister-boy 피그마에는 없었구만~ 뺄 이유는 없어서 추가하는게 맞을듯!!

**Comment by KoEonYack** [comment]
확인 완료!
