### ISSUE TITLE
[QA] 북마크 버튼 눌렀을때 반응 없음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#110]
![스크린샷 2023-09-12 오후 10 38 33](https://github.com/brave-people/Dev-Event-Web/assets/28642484/1a318462-6079-4df0-b089-cbbcb340326b)
> 검색 결과에서 북마크 버튼 클릭시 반응 없음

**Comment by leedoopal** [comment]
@KoEonYack 이건 로컬에서 확인해보니깐 수정 해주신 것 같은데..!? 확인해줄수있을까??

**Comment by KoEonYack** [comment]
@leedoopal 

이메일 알림을 놓쳤다 ㅜㅜ,,, 앗~ 잘되네 !! 확인 고마워!! 
이슈 닫을께!
