### ISSUE TITLE
[QA] 온라인 필터 검색시 오프라인 행사도 노출 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#111]
![스크린샷 2023-09-12 오후 10 40 56](https://github.com/brave-people/Dev-Event-Web/assets/28642484/36fdbe0e-50b4-4393-bcdf-73ea151a4b19)
> 필터에 온라인이라고 걸었으나 오프라인이라는 행사도 노출

**Comment by Resister-boy** [comment]
지금 무료가 체크가 되어있어서 그런 것 같아요! 지금 로직이 여러 이벤트 조건의 &&에 해당하는 이벤트가 아니라, ||에 해당하는 이벤트를 보여줘서 그래요!

**Comment by KoEonYack** [comment]
@Resister-boy 

앗 그렇네! 오키 재훈!
