### ISSUE TITLE
[QA] 추가 작업

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Web#114]
@Resister-boy님 안녕하세요!~! 프론트 작업중인 우성화입니다 :)
작업 중 여러 컴포넌트가 얽혀있어 건들기 어려운 부분들에 대해 개발 요청드립니다.

현재까지 작업한 브랜치는 `feature/qa` 브랜치입니다.
여기서 새 브랜치를 따셔서 작업하시거나, 기존에 작업하시던 `feature` 브랜치에 pull 받아 작업해주시면 감사하겠습니다.

### 1. 검색 결과 modal 띄운 상태에서 스크롤 시 아래 컴포넌트가 같이 스크롤 되는 이슈

https://github.com/brave-people/Dev-Event-Web/assets/39582981/6afb1052-ed97-4b00-8890-172ef26c6e5d

레이어로 작업해주셔서 스크롤 하게 되면 레이어 아래 컴포넌트가 스크롤이 되고 있는데요,
이 부분 수정해주시면 감사하겠습니다.
<br/>

<img width="320" alt="스크린샷 2023-09-26 오후 11 09 35" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/f35a4461-509d-48e3-b181-2e17268cd0cd">
<br/>
이 부분도 동일한 이슈가 있습니다.
전체적으로 살펴봐주시면 감사하겠습니다 🙇 

<hr/>

### 2. filter query string 수정
현재 검색 하게 되면 `search?kwd=x?tag=AI?type=대회` 이런식의 query string 형태로 보여지고 있는데요,
이 부분을 `search?kwd=x&tag=AI&type=대회` 형태로 수정해주시면 감사하겠습니다.

<hr/>

### 3. filter active 아이콘 수정
이 부분은 2번 이슈가 해결되어야 제대로 작업할 수 있을 것 같아 아직 작업을 못했는데요,
2번을 수정하시고나면 같이 부탁드립니다.

<img width="473" alt="스크린샷 2023-09-26 오후 11 14 25" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/c58ccdbc-fbb6-4217-87b7-dfa65c647bb5">
<br/>
위 이미지처럼 필터를 하나라도 선택했다면 active 된 아이콘으로 변경되어야 합니다 :)

<hr/>

### 4. 검색 후 리렌더링 버그

https://github.com/brave-people/Dev-Event-Web/assets/39582981/f94069e2-b5cc-4942-8dbd-b6608ca06d11

검색 후 검색 결과가 바로 보여지지 않고 리렌더링 되는 현상이 있습니다.

<hr/>

### 5. 검색 후 뒤로가기 버튼 클릭 시 리렌더링 버그

https://github.com/brave-people/Dev-Event-Web/assets/39582981/c9cf7137-e0a7-41b5-91e3-8df7f0e98163

검색 후 뒤로가기 버튼 클릭 시 페이지가 한번 더 렌더링이 되는 버그가 있습니다.

<hr/>

### 6. 검색 후 추천 검색어 클릭시 input, 검색 결과 헤더 바뀌지 않는 버그

https://github.com/brave-people/Dev-Event-Web/assets/39582981/760a950d-3d26-4c1e-95ee-906c5bbd7e1f

영상에서 '기술 일반' 태그 선택 시 Input, 검색 결과 헤더가 '기술 일반'으로 바뀌어야 하는데 바뀌지 않고 있습니다.

<hr/>

### 7. 내 이벤트, 내 정보 스타일 미적용
이 부분은 혹시 나중에 작업하려고 하신걸까요? 같이 작업해주시면 감사하겠습니다.
일정이 안될 것 같다면 말씀주세요 제가 작업하겠습니다!

---
cc. @KoEonYack

**Comment by leedoopal** [comment]
@Resister-boy 헉 전혀 아닙니다..!! 주말까지 가능하시다니.. 엄청 빠르시네요 👍 감사합니다

**Comment by Resister-boy** [comment]
1. 검색 결과 modal 띄운 상태에서 스크롤 시 아래 컴포넌트가 같이 스크롤 되는 이슈
modal이 생성될 때 modal 아래 페이지에 position fixed와 overflow hidden을 걸어줬습니다.

2. filter query string 수정
url을 관리하는 함수 urlUtil.tsx에서 해당 부분을 수정했습니다.

3. filter active 아이콘 수정
figma에서 active 시 해당하는 아이콘을 가져와서 active시 바뀌도록 했습니다.

4. 검색 후 리렌더링 버그
뭔가 의존성이 있는 것 같은데, 버그가 너무 간헐적으로 나와서 이유를 잘 못찾겠습니다..! 

5. 검색 후 리렌더링 버그
검색 후 뒤로가기를 누르면 페이지가 아래로 내려가는 화면을 연출하기 위해 setTimeout을 걸어줬었습니다. 그런데 실수로 url을 변경하는 함수를 setTimeout 내부에 넣지 않아 page가 바뀌면서 랜더링 + modalState가 바뀌면서 랜더링 되었던 것이 었습니다.  이렇게 상세하게 QA해주셔서 감사드립니다 ㅜㅠㅠ 

6. 검색 후 추천 검색어 클릭시 input, 검색 결과 헤더 바뀌지 않는 버그
수정했습니다!

7. 내 이벤트, 내 정보 스타일 미적용
이 부분은 일정이 안될 것 같습니다..! 정말 죄송합니다..!ㅜㅜㅠㅠ

**Comment by leedoopal** [comment]
이런 버그도 있네요..!
"테스" 검색어 입력 -> 검색 결과 없음 -> input에서 뒤로가기 시도 -> 뒤로가기 불가 & tags api 재호출

https://github.com/brave-people/Dev-Event-Web/assets/39582981/cf91b536-3ac9-4a6f-a3af-b766deb94732

**Comment by leedoopal** [comment]
@Resister-boy 
필터 쪽 약간 디버깅을 해봤는데 원인으로 의심되는 곳들이 몇가지 보이네요..!

### 1) router.replace()
전체적으로 router.push()가 자연스러워 보이는데.. 지금 구조가 쉽게 변경하기 어려운 구조네요;;
<img width="392" alt="스크린샷 2023-10-04 오전 12 08 07" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/2c9611be-ed90-4e96-b5f3-203af1116c52">

수정이 쉽게 가능하다면.. 이 부분을 레이어가 아니라 search 페이지로 넘기게 되면 좋을 것 같아요   

### 2) 불필요한 api 호출
- 최초 접속 시 tags api 2번 호출
  
https://github.com/brave-people/Dev-Event-Web/assets/39582981/4ba80068-6e24-4a8b-981b-62fbf25fa6f5

- '테스트' 키워드 검색시 tags api 6번 호출
  <img width="1274" alt="스크린샷 2023-10-04 오전 12 04 26" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/c30a58f6-d234-46d3-a2cf-d4823e72468a">

불필요하게 호출하는 것부터 해결해보면 좋을 것 같은데.. 한번 봐주실 수 있으실까요??

**Comment by KoEonYack** [comment]
@Resister-boy 당초 재훈이 예상 일정을 주었던것과 다르게 일정이 지연되고 있는데

남은 작업과, 얼마나 걸릴지 일정 재산정해서 공유주었으면 좋겠어

**Comment by Resister-boy** [comment]
@KoEonYack @leedoopal  죄송합니다..! 몇 일동안 급한 일정이 있어서 늦게 답드립니다..! 

먼저 4) 검색 후 리랜더링 버그는 해결완료했습니다. 그리고 뒤로 가기 불가 & tag api 호출되는 버그도 일단은 동작하도록 해결했습니다. 

하지만 근본적인 문제는 EventNull.tsx 컴포넌트의 useEffect()가 여러 번 호출되는 것이었고, 이 문제는 아직 해결이 안된 상태입니다. EventNull.tsx 컴포넌트는 필터가 적용된 Event가 하나도 존재하지 않을 경우 호출되는 컴포넌트입니다. 

그런데 이 컴포넌트가 마운트되지 않았음에도 불구하고 EventNull.tsx 컴포넌트 내의 useEffect가 동작하고 있습니다. 기존 tag api가 여러 번 호출되는 문제 역시 해당 api를 호출하는 로직이 EventNull.tsx 컴포넌트의 useEffect 내부에 존재했기 때문입니다. 현재는 해당 로직을 useEffect 바깥으로 옮기고 useSWR를 사용하여 호출하는 방식으로 여러 번 호출되지는 않지만, 근본적으로 EventNull.tsx 컴포넌트 내의 useEffect가 불필요하게 여러 번 호출되고 있는 것은 해결되지 않았습니다..! 직접 확인하실 수 있게 console.log(Hello, World')를 걸어놓았습니다. 

그리고 7) 내 이벤트, 내 정보 스타일링은 

![스크린샷 2023-10-10 041148](https://github.com/brave-people/Dev-Event-Web/assets/104838360/6d2f7975-e56f-49c3-a20a-46aa230ae29b)

위의 이미지처럼 북마크랑 My 태그가 나오게 작업하는 것으로 이해하면 될까요..? 제가 정확하게 이해한 것이 맞는지 몰라 여쭤봅니다..!

마지막으로 위의 내용을 작업하기 위해 로그인하게 되면 배포된 페이지로 리다이렉션되고, 쿠키도 배포된 페이지의 도메인으로 생성되는데 지금 환경에서는 어떻게 테스트 해야할지 여쭤보고 싶습니다..! 

첫 번째 에러를 해결하는데 얼마나 걸릴지 잘 모르겠지만, 최대한 3일 안으로 작업 마무리해보겠습니다..! 감사합니다..!

**Comment by leedoopal** [comment]
@Resister-boy 재훈님, 상세하게 살펴봐주시고 빠르게 수정해주셔서 감사합니다!!

(7)은 언약이한테 들었는데 아직 디자인이 안나왔다고 하더라구요, 제가 작업할게요!

제 생각엔 `EventNull.tsx` 컴포넌트가 마운트도 되고, 수시로 업데이트 되고 있는 것 같아보여요
지금 만드신 코드의 동작을 살펴보면..
#### 1) SSR
- isLoading: false -> EventNull 컴포넌트 동작
#### 2) CSR
- 그러고나서 아래의 useEffect를 타게 되는데요
- https://github.com/brave-people/Dev-Event-Web/blob/5aa885ddf7d879d893ce7f06a51a46e4e77758d7/components/common/item/ItemList.tsx#L31-L42
- (useEffect) isLoading: true
- (300ms 후) isLoading: false -> EventNull 컴포넌트 동작

이렇게 동작해서.. /events 페이지에서
`ItemList.tsx` 파일에서 로그를 찍어보시면 아래처럼 나옵니다 :)

<img width="553" alt="스크린샷 2023-10-10 오후 11 52 00" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/4fa63033-ae49-46b9-9a97-9e40071cc0bf">

로그가 두번씩 찍히는게 어디선가 중복해서 호출되는게 있는 것 같아보이는데..
거기까지는 찾아보지 않아서 😭 혹시 이 부분 한번 봐주실 수 있으실까요? 

그래서 이걸 해결하려면 제 생각에 
```typescript
const [ isLoading, setIsLoading ] = useState<boolean>(true);
```
isLoading의 초기값을 true로 두면 SSR일 때 true로 인식할테니 괜찮을 것 같은데요.

---

그런데 이 문제를 해결하고 나니 다음 버그가 또 보이네요;;

8) 월 선택 후 행사 검색하기 선택 시 리스트 업데이트

https://github.com/brave-people/Dev-Event-Web/assets/39582981/cb9af071-aba1-4b9f-9acc-7f6930380bf0
 
http://localhost:3000/calender?year=2023&month=09 에서
'행사 검색하기' input을 선택하면 하단 리스트가 업데이트 되는 것 같은 UI가 보여지는데요,
클릭시 레이어로 이동 되어야 하는 것은 아닐까요..??
아니면 엔터시에만 업데이트가 되어야한다던가,,
(아니라면 말씀주세요!)

9) 월 선택 -> 레이어 이동 -> 이벤트 페이지로 이동

https://github.com/brave-people/Dev-Event-Web/assets/39582981/c2b82d8e-b081-4c96-9320-d727d693c5aa

9-1) 이전 월로 이동시 버그

https://github.com/brave-people/Dev-Event-Web/assets/39582981/f2c9eb48-56c8-4003-aa00-cab41ec01896

위 동작까지 하고나서(9월인 상태에서 행사 검색)
이벤트 페이지로 돌아왔을 때 '이전 월' 선택을 하게 되면
텍스트는 10월로 되어있지만.. 9월 -> 8월로 이동하는 것 같아요.

9-2) 필터 선택 불가

https://github.com/brave-people/Dev-Event-Web/assets/39582981/170c3786-f0c8-4c4b-9b9d-45c5403548de

마찬가지로 (9) 동작까지 하고 나서 필터버튼을 선택하면 필터가 나오지 않아요ㅠ.ㅠ

**Comment by Resister-boy** [comment]
@leedoopal 
앗..! 퇴근하시고 고단하실텐데 이렇게 상세하게 리뷰해주셔서 감사합니다 성화님..!ㅜㅠㅠ 말씀해주신 방법으로 디버깅해보겠습니다! 그럼 다시 수정해서 커밋해놓겠습니다. 일단 추가로 찾아주신 버그까지 같이 목요일까지 완료해놓겠습니다. 다시 한 번 감사드립니다..!!!

**Comment by Resister-boy** [comment]
헉..! 일단 성화님이 말씀해주신대로 작성하니까 EventNull.tsx의 useEffect가 랜더링될 때 딱 한 번 실행됩니다..!ㅜㅠㅠㅠ 정말 대단하십니다..!ㅜㅠㅠ 감사해요!

**Comment by leedoopal** [comment]
@Resister-boy 
재훈님 필터가 까다로운데 수정해주셔서 감사해요!

[http://localhost:3000/search?type=스터디&tag=블록체인&location=온라인](http://localhost:3000/search?type=%EC%8A%A4%ED%84%B0%EB%94%94&tag=%EB%B8%94%EB%A1%9D%EC%B2%B4%EC%9D%B8&location=%EC%98%A8%EB%9D%BC%EC%9D%B8)

한가지 여쭤볼게 있는데, 위처럼 필터를 적용했을 때 `스터디 && 블록체인 && 온라인`인 행사가 나오는게 맞을까요?
아니면 `스터디 || 블록체인 || 온라인`인 행사가 나오는게 맞을까요??

지금은 and 조건으로 나오고 있어서 여쭈어봅니다 :)

**Comment by leedoopal** [comment]
제가 예전에 작업했던것과 컨플릭이 너무 많이나네요ㅠ.ㅠ 거의 다시 작업해야할 것 같아요 😭

**Comment by Resister-boy** [comment]
@leedoopal

1. 앗..! 저는 OR 조건으로 나오고 있는데, 어떻게 해야할까요..? @KoEonYack 
![image](https://github.com/brave-people/Dev-Event-Web/assets/104838360/6d2fd1f5-f9cc-406a-906e-90fcbb0dcd13)

2. 제가 불필요한 수정을 했을 수도 있어서 성화님 코드 다시 보면서 제가 수정할 수 있습니다..! 죄송합니다ㅜㅠㅠ 시간이 좀 필요할 수 있긴 한데 혹시 괜찮을까요..?

**Comment by leedoopal** [comment]
2. 헉 아녜요..! 기능은 다 잘 작동하는 것 같은데 구조가 바뀌어서 인지 css를 다시 수정해야 할 것 같아용ㅠ

**Comment by leedoopal** [comment]
@Resister-boy css 작업물은 다시 작업해서 추가해두었습니다!
그런데 버그가 자꾸 보이네요..! ㅠ.ㅠ 번거로우시겠지만 수정 부탁드려도 될까요?

🚨🚨 **pull 꼭 받고 진행해주세요!!** 🚨🚨

### mobile - 행사가 있지만 행사가 보이지 않는 버그
https://github.com/brave-people/Dev-Event-Web/assets/39582981/b7c568b1-4992-4e6d-8d51-23def49a4367

1) `테스트` 검색
2) `빅데이터` 태그 추가
3) 뒤로가기
4) 행사가 보이지 않음

<br/>

### desktop - '모바일' 태그로 검색 시 이벤트 보이지 않는 버그
http://localhost:3000/search?tag=모바일 로 검색 시 아래처럼 나와요

<img width="926" alt="스크린샷 2023-10-14 오후 9 07 02" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/b98ce6bc-2121-412e-9408-8a11116f2b49">


<br/>


### desktop - 필터 선택 시 버그
https://github.com/brave-people/Dev-Event-Web/assets/39582981/d08f89a1-792f-4115-aeb7-76f761e767c0

1) `백엔드` 선택
2) 행사 유형 - `스터디` 선택
3) `프론트엔드` 선택
4) 비용 - `유료 선택
5) `모바일` 선택
6) `모바일` 해제를 시도했지만 실패
7) `빅데이터` 선택 시 `모바일` 해제
8) `빅데이터` 해제를 시도했지만 실패

<br/>

### desktop - 불필요한 여백 발생
<img width="926" alt="스크린샷 2023-10-14 오후 9 09 49" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/790dff1b-36e2-4622-8fa0-40c325bb37af">

.search__list 영역이 잡혀서 불필요한 여백이 생기고 있어요

**Comment by Resister-boy** [comment]
앗..! 넵 그럼 제가 내일까지 수정해서 다시 올려두겠습니다..! QA 감사드려요..!ㅠㅠㅠㅜ

**Comment by Resister-boy** [comment]
안녕하세요 성화님! 
먼저 하루 딜레이되어서 죄송합니다!ㅜㅠㅠ 이슈에 달아주신 버그들은 모두 해결했습니다! 감사합니다!!

**Comment by leedoopal** [comment]
@Resister-boy 헛 아녜요..!! 버그 수정해주셔서 너무 감사해요 다 잘 작동하는 것 확인했습니다!

**Comment by KoEonYack** [comment]
@leedoopal @Resister-boy  후후 많은 작업이 있었군요~ 
오픈전까지 남은 작업이 있을까~?!

**Comment by leedoopal** [comment]
@KoEonYack 
기능은 끝난것같애!~! 
그런데 지금은 프로필 누르면 로그아웃이 되던데 내이벤트/내정보는 나중에 만드는거야??

**Comment by KoEonYack** [comment]
@leedoopal 

헛 댓글을 작성한것을 이제 보았어! 24시간 이내에 내가 답을 못하면 이건 놓친것이니 discord에서 리마인드 주어도 좋겠어!!

-----

아냐..! 버그인것 같네 ㅠㅠ,,, 내이벤트/내정모 만드는게 맞아..! 전반적으로 로그인 후처리가 기능이 이상해보여..!

내가 3주(?)전에 테스트했을때 로그인 기능 잘 되었는데 이상해졌네..!?

**Comment by leedoopal** [comment]
@KoEonYack 
나도 버그가 많긴한데.. 뭔가 나랑 버그가 다른 것 같은데?!

#### 회원가입 시 중복 아이디
'이미 존재하는 아이디입니다.' 나는 이렇게 나와!

#### 로그인 시 토큰 인증 실패 alert
<img width="704" alt="스크린샷 2023-10-24 오후 9 51 55" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/2a427143-3f2f-46d4-9781-34a297cca0d1">
@Resister-boy 
로그인 시도 하면 모달과 alert이 함께 나오고 있어요.

https://github.com/brave-people/Dev-Event-Web/blob/1019b16eb4ebcbc5a00a2f394b79feda9635ae50/components/layout/header/Header.tsx#L38

여기에 login() 함수를 호출해서 그런 것 같은데요, 호출하는 이유가 있을까요?

**Comment by KoEonYack** [comment]
@leedoopal 

문구 정도가 다른것이지~? 

앞으로 남은 작업은 

- 로그인 오류 수정
- 북마크 view 깨지는 문제 수정
- 내정보 view 깨지는 문제 수정

이것인가!!!

**Comment by Resister-boy** [comment]
@leedoopal 앗! 당시에 로그인을 어떻게 작업해야 할지 몰라 큰 의미 없이 넣어둔 것 같습니다..! 수정하셔도 될 것 같습니다..!

**Comment by leedoopal** [comment]
@KoEonYack 버그 고쳐놨어~! 기존 동작대로 동작하는 것 같은데 한번 확인 부탁할게!!

**Comment by leedoopal** [comment]
@KoEonYack 
나도 늦게봤네 😅 테스트 해줘서 고마워~!!
앗 오늘 완료되는 날이네! 전달해주면 이어서 작업할게!!

(요 이슈는 이제 종료할게)

**Comment by KoEonYack** [comment]
@leedoopal 

디자이너분의 맥북이 말썽이어서 오늘 완료는 안될것같아~ ㅠ____ㅠ!
