### ISSUE TITLE
Vercel 이관 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#115]
@leedoopal 

반가워~~~~~~~~~~!!

Vercel을 세원 계정에서 내 계정으로 옮겨야겠는데! 

(1) 현재 배포 개발 형상이 세원의 vercel에서 배포가 잘 되는지 확인 
(2) 세원의 vercel 도메인을 반납했을때 바로 반납한 도메인을 다른 계정에서 사용 가능할지 

두 가지 작업이 되어야하지 않을까 싶어!!

---------------------------------------

(1)을 위해서 세원이 어떤것을 하면 될까~? 
세원에게 버셀 접속해서 용감한친구들/dev-event-web의 dev 브랜치에 커밋/머지 발생하면 배포되도록 설정해달라고만 하면 될까~?!

(2) 세원의 vercel 프로젝트를 제거해서 https://d-dev-event.vercel.app, https://dev-event.vercel.app 도메인을 확보해야하는데 바로 확보가 되는지 모르겠어~ 

혹시 샘플 프로젝트 하나 배포하고, 타 계정에서 바로 획득이 되는지 테스트 가능할까~?!

**Comment by leedoopal** [comment]
(1) 말해준 것 처럼 진행하면 될 것 같애!! 👍 
(2) 흠 그럴수 있겠다..! 운이 나쁘게도 누군가 잽싸게 도메인을 채가면 못쓸 수도 있지 않을까??
공유하려면 무조건 비용이 발생하는거지? 😭

**Comment by KoEonYack** [comment]
@leedoopal 

(1) 세원에게 요청할께~~!!
(2) > 공유하려면 무조건 비용이 발생하는거지? 😭 -> 이 부분을 이해 못했어 ㅠㅠ,,, vercel은 내 계정에서 관리하면 되지 않을까~?!

**Comment by leedoopal** [comment]
@KoEonYack 
(2) 아 vercel 프로젝트 공유 말한거였어! 응응 그러면 될듯~!!

**Comment by KoEonYack** [comment]
@leedoopal 

확인 고마워~~!! 세원이 설정해주면 알려줄께!

**Comment by KoEonYack** [comment]
@leedoopal 

우리 어드민은 vercel에 어떻게 배포하고있어~?
organization 저장소 배포한다면.. 유료인데!!! 어떻게 하는것인지 궁금..!

**Comment by leedoopal** [comment]
@KoEonYack 
> 팀 프로젝트를 개인 레포로 클론해 무료(personal plan)로 배포하는 방법입니다.

나는 이렇게 하고 있어! 하하하

저렇게 하는게 최선일 것 같애..!!

**Comment by KoEonYack** [comment]
@leedoopal 

그렇구나~

> https://github.com/leedoopal/Dev-Event-Client

이거야~? last commit이 넘 오래전인데 private 저장소로 관리하나해서! 가능하다면 private 저장소로 운영하는것도 좋아보이고!!

**Comment by leedoopal** [comment]
@KoEonYack 
> For security reasons, you cannot change the visibility of a fork.
요렇게 나오네!

실제로 이 레포를 쓰지는 않고 나는 로컬에 클론받은 후 배포하고있어~!
저건 지워도 될 것 같아서 지우도록 할게!!

**Comment by leedoopal** [comment]
@KoEonYack 
저분은 에러가 발생 했네! 나는 그렇진 않았는데.. 

근데 내가 잘못 이야기 한 부분이 있어..! 
> 실제로 이 레포를 쓰지는 않고 나는 로컬에 클론받은 후 배포하고있어~!
저건 지워도 될 것 같아서 지우도록 할게!!

vercel 프로젝트 등록할 때 연결할 레포가 필요하네; 포크 뜬 다음에 진행해야할 것 같아ㅠ.ㅠ
밑에 이어서 설명할게!

1) vercel.com에서 프로젝트를 포크 뜬 레포로 등록해 (이미지는 어드민)
<img width="396" alt="스크린샷 2023-10-20 오후 7 43 15" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/c35910c5-6f97-4d65-b287-963621546740">

- 등록하면 위처럼 프로젝트가 생기는데,
- env 설정은 "세팅 -> Environment Variables" 에서 해주면 되고
- dev branch를 dev로 연결하려면 또 따로 세팅을 해줘야해!
  - 세팅 - Domains
  -  <img width="926" alt="스크린샷 2023-10-20 오후 7 48 32" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/d8551dea-a755-4298-b7cd-472de6178e22">


<br/>

2) 그러고 아래 링크 참고해서 pnpm, yarn, npm 중 있는걸로 로컬에서 vercel cli를 설치하고
https://vercel.com/docs/cli

3) 터미널에서 `vercel login` 해주고

4) `vercel build && vercel deploy` 해주면 끝이야!

**Comment by KoEonYack** [comment]
@leedoopal 

우와 넘 친절한 설명이야!! 덕분에 에러 하나 안만나고 너무 테스트 잘했어..! 

신기하네.. 사용자 저장소를 등록하고, 사용자 저장소 브랜치로 버셀에서는 설정했는데 로컬에서 다른 저장소의 org를 배포할 수 있다는것이..!

테스트를 위해서 brave-people/dev-event-web에 deploy/1020 브랜치를 만들었어! 테스트 끝나고 삭제할께!

------------------------

배포를 위해서 vercel에 로그인해야하니깐 성화 계정으로 옮겼으면 좋겠는데 어때~?!

만약 좋다면...!? 

1. 개발/리얼 환경변수 성화에게 전달 
2. 세원의 도메인 반납 
- vercel 프로젝트에서 살짝 도메인 이름만 바꾸어놓고 성화 계정에서 vercel 도메인 획득 후 잘 배포되는지 확인 

이정도만 하면 이관 작업은 마무리할 수 있지 않을까!!?

**Comment by KoEonYack** [comment]
@leedoopal 

일단 성화 vercel에다가 아무 도메인으로 개발/리얼 배포해두고!(혹시 환경변수 필요하닝?)

세원이랑 시간 잡아서 개발 도메인 샤샥 바꾸고 리얼 도메인 샤샥 바꾸면 10초 정도 사이에 누가 가져가지는 않을것같아!

10초 사이에 뺏긴다면..? 눈물을 머금고 다른 도메인을 쓰장!

**Comment by KoEonYack** [comment]
@leedoopal 

세원에게서 vercel 도메인을 가져왔어!

세원이랑 해보니 3분도 안걸리는듯!! 성화 vercel 계정으로 이관할 시간을 정해보자!

**Comment by leedoopal** [comment]
@KoEonYack 
구래~~!! 좋아!

**Comment by KoEonYack** [comment]
@leedoopal 

일단 급한것은 아닌것 같긴한데!!

개발/리얼에 성화가 배포가 필요한 시간이 오면 알려줘~ 그때 샤삭 도메인 넘기는 작업하면 될듯!

**Comment by leedoopal** [comment]
@KoEonYack 어느덧.. 해가바뀌었네... 이번주 금요일 오후 6시 어때?
