### ISSUE TITLE
디자인 이슈 및 잔여 이슈 처리

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#116]
# 작업 대상
## 프로젝트 설정 
- [x] .gitignore 설정 (intelij + vscode에서 개발하기 때문에 추가 필요)
- [x] prettier 린트 설정 

## 마이페이지
- [x] 현재 프로젝트의 코드가 prettier가 적용되어있지 않음. 일단 마이 페이지 연관 코드부터 prettier 작업 수행 필요 
- [x] npm run build시 타입 오류 수정
- [x] 마이페이지 CSS 추가 작업

## 개발자 행사
- [x] 개발자 행사 카드 변형된 디자인에 맞추어 css 수정 + 반응형까지 (@leedoopal)
- [x] 잔여 버그 수정 (@leedoopal)

## 내 행사 
- [x] 디자인 반영 필요 (작업하려면 개발자 행사 카드 css 수정 작업이 필요해!)

---------------------------------------------------------------------------
# 메모
## 작업 브랜치
- origin/feature/v2

## prettier
- 어드민이랑 Prettier 설정이 조금 다르거든..? 통일하는게 좋을까?(왜 나는 처음 설정할때 다르게 한 것인가..;ㅅ;) 성화가 결정하면 좋겠어!!
   - 어드민과 통일 완료
## 계정
- 로컬&개발환경에서 테스트하기 편하라고 계정 하나 만들어놓음!
- id: test1 / pw: 123456

**Comment by leedoopal** [comment]
> 어드민이랑 Prettier 설정이 조금 다르거든..? 통일하는게 좋을까?(왜 나는 처음 설정할때 다르게 한 것인가..;ㅅ;) 성화가 결정하면 좋겠어!!

통일하는게 좋을 것 같애! 어드민걸로 통일해두될까..?!

**Comment by leedoopal** [comment]
#### 업데이트 사항
- Item 현재 피그마에 맞추어 css 수정
- 패키지 매니저 npm -> pnpm으로 변경
- prettier 전체 파일에 적용

아이템 카드 css 수정해봤는데 한번 봐줄래? 

아래 태그 같은 경우는 PC는 background(1번), 모바일은 border(2번)로 하면 될까?
- 1번
  <img width="254" alt="스크린샷 2024-01-12 오후 9 58 14" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/efc44a56-f491-4e9f-b514-82bd4dd7cd38">
- 2번 
  <img width="246" alt="스크린샷 2024-01-12 오후 9 58 22" src="https://github.com/brave-people/Dev-Event-Web/assets/39582981/ffe54cb0-371f-45df-a6ee-5b7782a4df89">


cc. @KoEonYack

**Comment by KoEonYack** [comment]
@leedoopal 

> 어드민이랑 Prettier 설정이 조금 다르거든..? 통일하는게 좋을까?(왜 나는 처음 설정할때 다르게 한 것인가..;ㅅ;) 성화가 결정하면 좋겠어!!
>> 통일하는게 좋을 것 같애! 어드민걸로 통일해두될까..?!

헉~!! 이멜을 놓쳤네 ㅠㅠ,,, 내가 하루 안에 답을 못준다면 메신저로 리마인드 주어도 좋아~~~!!!

굳뜨! 통일하는게 좋아!

**Comment by KoEonYack** [comment]
@leedoopal 

우와~~~ 장족의 발전이 있었다!!! 
내가 발견한 부분을 써봤어!! 

-------------

<img width="593" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/73e4948e-0538-48bd-b00f-22bc6d1dbd38">

> 일시 부분이 길어지면 짤리고 있어!

------------------------------------------------------------------------

![스크린샷 2024-01-12 오후 11 57 24](https://github.com/brave-people/Dev-Event-Web/assets/28642484/bad1f8d3-0447-4d88-ad4e-c5b724882fe0)

> 모짜렐라 치즈처럼 늘어나는데~ 이 부분은 아직 안된 것일까!!?

------------------------------------------------------------------------

<img width="418" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/de5c7006-d33d-4be0-bd9d-6c3a3571040e">

> 종료시 어두운 카드가 섬네일보다 늘어났는데~ 이 부분은 기능인가!!?

------------------------------------------------------------------------

<img width="511" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/cd07da3b-051c-44b6-ab91-795586560f75">

> 좌측이 css 적용 결과이고 우측이 디자인인데 행사 제목 - 날짜, 날짜 - 태그 간격이 디자인과 상이한것 같아!

**Comment by KoEonYack** [comment]
@leedoopal 

> 문의사항
> 아래 태그 같은 경우는 PC는 background(1번), 모바일은 border(2번)로 하면 될까?
> 피그마가 좀 헷갈리네;

2번대로 하는게 맞아!

**Comment by leedoopal** [comment]
@KoEonYack 꼼꼼하게 확인해줘서 고마워!~!

> 2번대로 하는게 맞아!

2번대로 하는게 맞다는건 PC, 모바일 모두 2번이라는거지??

> 좌측이 css 적용 결과이고 우측이 디자인인데 행사 제목 - 날짜, 날짜 - 태그 간격이 디자인과 상이한것 같아!

요거 수정하려는데 앞으로 디자인이 바뀔 일은 없는거지?!

**Comment by KoEonYack** [comment]
@leedoopal 

헛... 이제 보았다...!
figma를 보면 또 변경되었어 ㅠㅠ,,, 이젠 태그에 background가 들어가!

**Comment by leedoopal** [comment]
@KoEonYack 
허걱 그렇구나..! 최종 완성된 다음에 한번에 고치고 싶은데 이제 정말 완성일까?!

**Comment by KoEonYack** [comment]
@leedoopal 

설 잘 보냈어~??!

디스코드 보시다싶이!! 수정사항이 있어서 수정하고있어..!

디자인 변경 사항이 많아서 작업에 힘들었을것 같아 ㅜㅜ..

디자인 작업 완료되면 연락할께!! 고마워!😊

**Comment by leedoopal** [comment]
@KoEonYack 
고마워 히히 나는 잘 보냈어~! 새해 복 많이 받아!! 🍀 
알겠어!~! 기다리고 있을게!
