### ISSUE TITLE
깃허브 로그인 되지 않음 (버그)

### ISSUE THREAD

**Issue by skmn3** [brave-people/Dev-Event-Web#14]
![image](https://user-images.githubusercontent.com/81291090/178414658-dda26580-8372-4fe7-9595-8fed07e5baac.png)

![image](https://user-images.githubusercontent.com/81291090/178412660-87fb14b5-d353-4eea-8eac-42c5eca98641.png)

- https://dev-event.vercel.app/events
    - 새롭게 만들어진 웹 페이지에서 예상치 못한 오류가 발생하였습니다.
    - 깃허브로 로그인하는 것이 되지 않습니다. ( 카카오 구글 네이버는 모두 잘 작동됩니다 👍 )
    - 서버측 문제인 것 같으나 웹 페이지는 여기서 개발하시는 것 같아 문의 드려봅니다.
 
감사합니다.

@ohh31

**Comment by ohh31** [comment]
이슈 확인했습니다! 빠른 시일 내에 해결하겠습니다.
감사합니다 :)

**Comment by KoEonYack** [comment]
@skmn3 님 제보 감사합니다~ 👍 

해당 문제는 Github 계정에서 이메일을 공개하지 않 이메일 정보를 읽을 수 없어 생긴 문제입니다

해결하려면 [Github 로그인 고객센터](https://github.com/brave-people/Dev-Event-Server-Wiki/blob/main/_%EA%B3%A0%EA%B0%9D%EC%84%BC%ED%84%B0/%EC%86%8C%EC%85%9C%EB%A1%9C%EA%B7%B8%EC%9D%B8.md)글을 통해서 해결하실 수 있습니다!

더불어 로그인에 실패하면 해당 문서로 리다이렉션 될 수 있도록 수정을 완료한 상태입니다!!

다시 한 번 감사드리며

평안한 밤 보내세요^^

**Comment by skmn3** [comment]
감사합니다. 해결되었습니다!! 👍
