### ISSUE TITLE
[💡 개선 아이디어] 행사 `:`과 `시간` 사이 공백 추가

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#20]
@ohh31 

![image](https://user-images.githubusercontent.com/28642484/179243970-041a3eea-e452-4840-84c4-291aa6e9ae46.png)

첫 번째 행사와 다르게 두 번째 행사의 `:` 와 `시간` 사이 공백이 없습니다~!

**Comment by ohh31** [comment]
버그 이슈 확인했습니다! 빠른 시일 내에 수정하도록 하겠습니다. 
감사합니다 :)

**Comment by ohh31** [comment]
해당 개선사항을 반영해 배포했습니다! 
추가 이슈사항이 있다면 말씀해주세요~!
