### ISSUE TITLE
[💡 개선 아이디어] header 데브 이벤트 로고 옆 텍스트 로고 추가

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#21]
@ohh31 

## 현재

![스크린샷 2022-07-17 오후 11 03 30](https://user-images.githubusercontent.com/28642484/179401976-70e10298-a60a-4e5b-9c3a-cb6ceaf0e655.png)
- 현재의 경우 타 사이트와 다르게 DEV EVENT 이미지 로고 옆 텍스트 로고가 없습니다~

---------

## 개선 제안 
![스크린샷 2022-07-17 오후 11 05 08](https://user-images.githubusercontent.com/28642484/179402074-f8e3bd34-fd34-4c3e-a0fb-dc6af9a36da9.png)
- DEV EVENT 로고 옆 텍스트를 추가해봤습니다~
- 다른 사이트 처럼 로고에 어울리는 DEV EVENT 텍스트를 그리면(타이포 그라피라고 해야할까요?) 좋겠지만 마땅치 않다면 그냥 텍스트 추가도 어떨까 생각이 듭니다

**Comment by ohh31** [comment]
제안주신 아이디어는 디자이너와 고려해보겠습니다. 감사합니다! :)

텍스트 로고가 없는 서비스도 있는데 텍스트 로고가 있으면 좋다고 생각하시는 이유가 있으실까요?? 
말씀해주시면 개선 과정에서 큰 도움이 될 것 같습니다~! 👍

**Comment by KoEonYack** [comment]
@ohh31 

![스크린샷 2022-07-19 오후 10 48 59](https://user-images.githubusercontent.com/28642484/179766452-e090e79e-63a7-44fe-80ea-074f5604a3a6.png)
> 역으로 다른 서비스 이름을 가리고, 데브 이벤트 텍스트 로고를 추가한 케이스

1. 데브 이벤트 로고는 대중적으로 알려진 로고가 아니기에 로고만 봤을때 어떤 사이트인지 알기가 쉽지 않다는점!

2. 지금은 페이지 상단에 개발자 행사는 모두 Dev Event에서 라는 문구가 있지만 해당 부분을 다른 개발자 행사 소개 배너로 활용한다면 사이트 이름을 직관적이게 알리기 힘들어진다는점 

3. 개발자 행사 다시보기, 개발자 모임을 추가했을때 Header에 일괄적으로 Dev Event라는 사이트라는 정보를 전달해 주기 위함

이정도 아닐까 생각이 드네용~
