### ISSUE TITLE
[💡 개선 아이디어] 종료된 행사 접기 -> 펼치기 기능 추가

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#22]
@ohh31 

## 현재

![스크린샷 2022-07-17 오후 11 07 18](https://user-images.githubusercontent.com/28642484/179402177-818e3615-d7ff-4ec2-8bde-bea74de33cb6.png)
- 현재 달의 종료된 행사 갯수가 늘어나서 다음달 행사를 보려면 스크롤 압박이 심합니다~

## 개선 제안 
![스크린샷 2022-07-17 오후 11 10 08](https://user-images.githubusercontent.com/28642484/179402323-3de2c5f0-7a93-4f19-a26b-2476e149a2be.png)
- 이번달 종료된 행사는 묶어서 보여주는게 어떨까 제안해봅니다~~

**Comment by ohh31** [comment]
제안주신 아이디어 확인했습니다! 
저도 고민하고 있던 부분이라 디자이너와 논의해 빠른 시일 내에 개선해보겠습니다. 감사합니다 👍

**Comment by ohh31** [comment]
해당 이슈 반영되어 클로즈 하겠습니다! 감사합니다 :)
