### ISSUE TITLE
[🐞 버그제보] 검색 결과 URL을 브라우저에 직접 입력시 검색결과 없음

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#23]
@ohh31 

버그를 제보합니다~

![스크린샷 2022-07-19 오후 10 16 10](https://user-images.githubusercontent.com/28642484/179759351-878888db-4d34-4276-95fe-1f63504fc0ad.png)
> (Figure 1) 데브 이벤트 웹 페이지 내에서 검색시 검색 결과가 나옵니다.

-------

![스크린샷 2022-07-19 오후 10 15 50](https://user-images.githubusercontent.com/28642484/179759277-b538cd10-e020-48d9-a269-e08929ad6a80.png)
> (Figure 2) (Figure 1)에서 획득한 URL인 https://dev-event.vercel.app/events?keyword=CMC 을 브라우저에 입력하여 이동한 경우 검색결과가 없습니다~

**Comment by ohh31** [comment]
감사합니다 :) 빠른 시일 내에 수정하도록 하겠습니다.

**Comment by ohh31** [comment]
해당 이슈 해결해 배포하였습니다!
추가적인 이슈가 있으시면 말씀해주세요! 감사합니다 :)
