### ISSUE TITLE
[💡 개선 아이디어] 현재 진행중 행사에서 종료된 행사 갯수 제외

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#24]
@ohh31 

![스크린샷 2022-07-19 오후 10 19 32](https://user-images.githubusercontent.com/28642484/179760019-d3ee1ca4-b81e-454a-b71c-35482f62c9ca.png)

> 데브 이벤트 메인 페이지에 노출되는 행사는 50개가 맞으나 종료된 행사 11개입니다.
> 50 - 11 = 39개의 행사가 __예정__ 된 것이므로 `현재 50개의 개발자 행사 진행 중` -> `현재 39개의 개발자 행사가 예정되어 있어요!` 문구를 제안해봅니다!

**Comment by ohh31** [comment]
피드백 감사합니다 :)
이 전에 남겨주신 스크롤 이슈도 함께 고려했을 때 메인 페이지에서는 종료된 행사를 제외하고 보여주는 것이 좋겠다는 생각이 듭니다.
저도 데브이벤트 웹을 사용하면서 종료된 행사를 조회했던 경우가 없고, 종료된 행사는 월별 조회에서 가능하니
메인페이지의 종료된 행사를 위해 추가적인 개발을 하기보다는 제거하는 방향으로 개선해보겠습니다!

**Comment by KoEonYack** [comment]
@ohh31 

종료된 행사는 제거하는 방향 좋습니다~~~

**Comment by ohh31** [comment]
해당 이슈 반영되어 클로즈 하겠습니다! 감사합니다 :)
