### ISSUE TITLE
[🐞 버그제보] 개발자 행사 시간 미노출

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#25]
@ohh31 

일부 개발자 행사에서 행사 시간이 노출되지 않는 문제가 있어요~

![스크린샷 2022-07-19 오후 10 24 43](https://user-images.githubusercontent.com/28642484/179761228-317dec54-6929-4453-86bd-a31c3932eec8.png)
> 시간 미노출 문제가 발생하는 행사!

![스크린샷 2022-07-19 오후 10 25 20](https://user-images.githubusercontent.com/28642484/179761366-61d80f41-cfe5-40b0-bea0-d71760675dcf.png)
> 시간 미노출 문제가 발생하는 행사 응답  Json
> start_time, end_time에 값이 있습니다!

**Comment by ohh31** [comment]
해당 형식의 일정이 개발 상 반영되지 않아 발생한 버그였습니다.
버그를 해결해 배포하였으니 추가 이슈가 있다면 말씀해주세요! 👍
