### ISSUE TITLE
[💡 개선 아이디어] SEO 검토(?)

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#26]
@ohh31 

meta tag로 `google-site-verification`이 있는것으로 보아 SEO 작업이 된 것으로 아는데요~

![스크린샷 2022-07-19 오후 10 27 49](https://user-images.githubusercontent.com/28642484/179761917-8809f909-7719-4567-bfc6-7bbe9be5e492.png)

최소 2주 전에 마친것으로 아는데 다만 검색했을때 결과가 나오지 않는 상황입니다~

![image](https://user-images.githubusercontent.com/28642484/179762809-785c0556-50f5-4d92-a24f-70e1150c4051.png)
> 구글 `개발자 행사` 검색시 최상단 노출

Github에 종속된 저장소 Dev-Event는 현재 30%의 트래픽이 구글 검색으로 유입되며, 개발자 행사 검색시 최상단에 노출되는 만큼 

검색 엔진에 노출되는 것은 서비스를 알리는 어떠한 방법보다 최고의 방법인데요~

https://intrepidgeeks.com/tutorial/next-js-optimization

위의 블로그 뿐만 아니라 next.js로 SEO 최적화 하는 다양한 방법이 있는데 다양하게 적용이 필요해 보입니다... 

데브 이벤트 검색했을때 버셀 웹 페이지가 나오면 성공인걸로..!

**Comment by ohh31** [comment]
이제 데브이벤트 웹 , 데브이벤트 검색하면 구글 상단에 뜨는데 
개발자 행사 검색했을 때는 안 뜨네요,,, 계속 적용해보겠슴다

**Comment by ohh31** [comment]
데브이벤트, 데브이벤트 웹을 선택했을 때 검색 결과가 나오도록 개선했기 때문에 우선 close 하고 
저번 회의 때 이야기했던 것처럼 개발자 행사 개별 검색 시 나올 수 있도록 추후 개선해보겠습니다! 
의견 감사합니다 :)
