### ISSUE TITLE
[🐞 버그제보] 태그 색상이 변경되어서 표시되지 않는 문제

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#33]
@ohh31 

비 많이 오는데 잘 지내나~~~~?! ☂️☂️☂️

---------------------

![스크린샷 2022-08-09 오후 9 53 42](https://user-images.githubusercontent.com/28642484/183651769-18de84fa-d508-488f-9205-f20a2c19716a.png)

![스크린샷 2022-08-09 오후 9 57 04](https://user-images.githubusercontent.com/28642484/183652521-0720144c-73ad-4db4-8970-2e9481a3577e.png)

관리자 페이지에서 태그 색상을 변경했을때 기본 색상값이 계속 보여지네!! 버그로 제보함!! (미구현일수도 있지만!)

**Comment by ohh31** [comment]
넵 아직 미구현된 기능입니다! 
혹시 태그 컬러와 관련해 변경된 스팩을 어디서 확인할 수 있을까요??

**Comment by ohh31** [comment]
오 아직 미구현이에요! 오늘 중에 구현할 예정입니다 :)

**Comment by KoEonYack** [comment]
@ohh31 

멋쩌 세원!!!! 고마워유~~~~!
