### ISSUE TITLE
[🐞 버그제보] 즐겨찾기 UI update 안되는 증상

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Web#34]
버그이슈 처음남기네요! 반가워요~~

즐겨찾기에 등록했는데 별 모양의 색이 바뀌지가 않아요;ㅅ;

![스크린샷 2022-08-10 오후 8 14 05](https://user-images.githubusercontent.com/39582981/183888187-542b7d95-604b-4c84-b96c-5c2af80099d8.png)

```
POST /front/v1/favorite/events/96

response
{
  "status_code":400,
  "status":"FRONT_FAVORITE_400_02",
  "message": "이미 등록된 개발자 행사 찜 입니다."
}
```

**Comment by leedoopal** [comment]
96번만 그러네요..!

**Comment by ohh31** [comment]
헉 확인해보겠습니다!! 버그 발견 감사합니다 👍

**Comment by ohh31** [comment]
찜 기능은 미래 이벤트와 종료된 이벤트가 따로 처리되고 있었는데 서버와 프론트에서의 종료된 이벤트의 기준이 달라 발생한 문제였습니다! 
프론트에서 모두 처리하는 것으로 수정해 문제해결 하였습니다!
추가적인 이슈가 있으시면 남겨주세요! 버그 제보 감사합니다 :)
