### ISSUE TITLE
[🐞 버그제보] 내 이벤트 조회 결과 없음

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Web#35]
```
POST /front/v1/favorite/events/96

response
{
  "status_code":400,
  "status":"FRONT_FAVORITE_400_02",
  "message": "이미 등록된 개발자 행사 찜 입니다."
}
```

제가 찜을 했다면 내 이벤트 조회 시 하나가 나와야 할 것 같은데요,
![스크린샷 2022-08-10 오후 8 19 33](https://user-images.githubusercontent.com/39582981/183888894-df08e2ab-abad-48d2-a3e7-74999bb81339.png)
그런데 스크린샷처럼 찜한 이벤트가 하나도 없어요.

```
https://dev-event.vercel.app/_next/data/txD3zP8L2uBLXyPxG3qnB/myevent.json

response
{"pageProps":{"isLoggedIn":true},"__N_SSP":true}
```

api가 문제인지 프론트에서 내려줄 때 버그가 있는건지 잘 모르겠네용;ㅅ;

**Comment by ohh31** [comment]
내 이벤트에 문제가 많군요....! 이 부분도 다른 이슈들과 함께 확인해보겠습니다 
감사해요 :)

**Comment by ohh31** [comment]
해당 이슈도 마찬가지로
찜 기능은 미래 이벤트와 종료된 이벤트가 따로 처리되고 있었는데 서버와 프론트에서의 종료된 이벤트의 기준이 달라 발생한 문제였습니다!
프론트에서 모두 처리하는 것으로 수정해 문제해결하였습니다!
버그 제보 감사합니다 :)
