### ISSUE TITLE
[💡 개선 아이디어] 찜하기 속도 느림

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Web#36]
@KoEonYack @ohh31 
찜하기 클릭시 속도가 좀 느린 것 같은데 BE 이슈인가요 FE 이슈인가요?
아니면 그냥 정상 속도 일까요?

![스크린샷 2022-08-10 오후 10 06 46](https://user-images.githubusercontent.com/39582981/183909162-2bacbb1c-8db9-4590-86d8-859c13519676.png)
찜 추가/제거 모두 600~700ms 정도 걸리는 것 같아요.

![스크린샷 2022-08-10 오후 10 06 52](https://user-images.githubusercontent.com/39582981/183909229-4a73c378-4e9e-42b9-a18d-bd39dc569be4.png)

확인해보니 getToken에서 시간이 좀 걸리는 것 같은데 찜할 때 마다 토큰을 새로 가져와야하나용??
왜 필요한 것인지 잘 모르겠어요..!

**Comment by KoEonYack** [comment]
![스크린샷 2024-05-11 오후 6 16 00](https://github.com/brave-people/Dev-Event-Web/assets/28642484/b2932d65-0d45-48d0-a991-16835643ec77)

신규 서버를 통하여 200ms 이내로 동작
