### ISSUE TITLE
[💾 데이터 추가] 08/13, 08/15 행사 등록 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#39]
@ohh31 

이번주는 세원의 담당이다! (이번주 금요일까지~)

지난주 토요일이랑 오늘 행사 등록  요청할께!

라인 변경된것으로 보이는 행사 중에서 행사 위치를 옮겨서 라인 변경으로 뜨는것도  있으니 잘 봐야해~

**Comment by ohh31** [comment]
행사 등록했습니다!
