### ISSUE TITLE
[ 📣 프론트 공지] v2 행사 날짜 유형 및 조건 확인

### ISSUE THREAD

**Issue by ohh31** [brave-people/Dev-Event-Web#53]
v2 전환 전에 **행사 날짜 유형과 조건**을 얼라인하면 좋을 것 같아 공유드립니다! 
추가/수정해야할 부분이 있다면 말씀해주시고 확인 후 이모지 부탁드립니다 !

* **1-1) 당일치기 행사 - 날짜만 있는 경우 ex) 2021년 5월 3일 (수)**
start_date_time && !end_date_time
use_start_date_time = N
use_end_date_time = null

* **1-2) 당일치기 행사 - 날짜, 시작시간과 종료시간이 있는 경우 ex) 2021년 5월 3일 (수) 10:00~15:00**
start_date_time &&  end_date_time 
start_date_time === end_date_time (날짜만)
use_start_date_time = Y
use_end_date_time = Y

* **1-3) 당일치기 행사 - 날짜와 시간이 있는 경우 ex) 2021년 5월 3일 (수) 10:00**
start_date_time && !end_date_time
use_start_date_time = Y
use_end_date_time = null

* **2-1) 마감일만 있는 행사 - 날짜만 있는 경우 ex) 2021.05.03(수) 까지**
!start_date_time && end_date_time
use_start_date_time = null
use_end_date_time = N

* **2-2) 마감일만 있는 행사 - 날짜, 시간 있는 경우 ex) 2021.05.03(수) 10:00까지**
!start_date_time && end_date_time
use_start_date_time = null
use_end_date_time = Y

* **3-1) 시작, 종료일이 있는 행사 - 날짜만 있는 경우 ex) 2021.05.03(수) ~ 2021.05.05(수)**
start_date_time && end_date_time
use_start_date_time = N
use_end_date_time = N

* **3-2) 시작, 종료일이 있는 행사- 날짜, 시간 있는 경우 ex) 2021.05.03(수) 10:00 ~ 2021.05.05(수) 13:00**
start_date_time && end_date_time
use_start_date_time = Y
use_end_date_time = Y

- **3-3) 시작, 종료일이 있는 행사 - 시작 시간만 있는 경우 ex) 2021.05.03(수) 10:00 ~ 2021.05.05(수)**
start_date_time && end_date_time
use_start_date_time = Y
use_end_date_time = N

* **3-4) 시작, 종료일이 있는 행사- 종료 시간 있는 경우 ex) 2021.05.03(수) ~ 2021.05.05(수) 13:00**
start_date_time && end_date_time
use_start_date_time = N
use_end_date_time = Y

**Comment by leedoopal** [comment]
@ohh31 헉 메일을 지금 봤어요;; 미안해요;; 😭 
null 없이 'Y' | 'N' 으로만 보내려 했는데 괜찮을까요?

---
@KoEonYack 
선생님 반가워요~~ v2 event 생성하려는데 에러가 나네요 😢 
이 에러 왜 나는지 알 수 있을까요?

POST admin/v2/events
payload
```json
{"title":"v2 test","description":"","organizer":"cindy","display_sequence":0,"event_link":"https://www.naver.com","start_date_time":"2022-09-22T17:00","end_date_time":"2022-09-22T00:00","tags":[{"id":11,"tag_name":"ㅎㅇㅎㅇ1","tag_color":"#667CF1"}],"cover_image_link":"https://brave-people-3.s3.ap-northeast-2.amazonaws.com/dev/DEVEVENT/2022-09-22-23-25-0038-00e376e2.png","event_time_type":"DATE","use_start_date_time_yn":"Y","use_end_date_time_yn":"N"}
```
response error
```json
{"status_code":500,"status":"ERROR_500_00","message":"INTERNAL SERVER ERROR","errors":["Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement"]}
```

**Comment by KoEonYack** [comment]
@leedoopal 

DB 스키마가 업데이트 안되어있었어요! 고쳤어요~~~~~!

![스크린샷 2022-09-22 오후 11 40 14](https://user-images.githubusercontent.com/28642484/191777288-6f7ec1b4-cc85-4c18-8629-ef1a52e1f264.png)

신디의 행사 등록에 성공하였어요~~!

**Comment by KoEonYack** [comment]
@leedoopal  
> null 없이 'Y' | 'N' 으로만 보내려 했는데 괜찮을까요?

제가 NULL을 보내달라고 요청을 했어요~!! 
use_{start|end}_date_time은 {start|end}_date_time의 Time값이 있는지를 알려주는 flag라 만일 {start|end}_date_time이 null이라면 use_{start|end}_date_time도 null이 맞지 않을까 생각이 들었어요~

좌우간 서버는 넣은 데이터 그대로 보여주어서요~~~ 그냥 의견만 드릴뿐이랍니다~~~~!

**Comment by leedoopal** [comment]
@KoEonYack 
오 완전 로켓 답변이에요 너무 고마워요!

---
아 그랬군요~~~~ 그것도 맞는 말이네요
프론트에서는 체크박스로 사용 유무를 체크하고 있다보니 on('Y') off('N') 외의 다른 값을 넣기가 애매해서요
차라리 use_{start|end}_date_time 을 아예 안보내면 서버에서 null로 바꿔주나요?

**Comment by KoEonYack** [comment]
@leedoopal 


v3 test 제목으로 use_{start|end}_date_time을 안보냈을때 GET 응답값이에요~

![스크린샷 2022-09-22 오후 11 51 04](https://user-images.githubusercontent.com/28642484/191780004-810112de-2fd6-4138-b492-eba98eaa950d.png)

DB에 저장된 값이 없으니 null이 내려온답니다!

**Comment by KoEonYack** [comment]
@ohh31 

나도,, 메일 알림을 놓쳐서 이제 보았지만....!
멋찐 정리야~!! 💯

**Comment by leedoopal** [comment]
@KoEonYack 
> {start|end}_date_time의 Time값이 있는지를 알려주는 flag

Time은 프론트에서 늘 T00:00을 붙여서 보내기 때문에 null이 붙는게 애매한 것 같아요.
생성시에는 괜찮아 보이는데, 수정시에는 time(T00:00)가 늘 들어오고있어서 
가능은 하지만.. 복잡한 코드가 될 것 같아요


만약 아래처럼 된다면 개발해도 알아보기 좋을 것 같아요~!

**time이 없다면**
프론트에서 `YYYY-MM-DD` 로 생성,
서버에서도 그대로 `YYYY-MM-DD`로 반환.

**time이 있다면**
프론트에서 `YYYY-MM-DDThh:mm`로 생성,
서버에서도 그대로 `YYYY-MM-DDThh:mm` 반환

그럼 시간이 없으니 null check 편함
시간이 있다면? -> useDateTime 'Y' | 'N' 체크

**Comment by KoEonYack** [comment]
@leedoopal 아~~~~ 선생님 그게 아니라요~~~~!!

예를 들어서 
```
2-1) 마감일만 있는 행사 - 날짜만 있는 경우 ex) 2021.05.03(수) 까지
!start_date_time && end_date_time
use_start_date_time = null
use_end_date_time = N
```

이렇게 마감일만 있다면 start_date_time = null, use_start_date_time = null 을 보내자는 말이었어요~~!

스크럼이 있는 금요일이니 에매한것은 이따 스크럼때 의견주어도 좋아요~~!!!!

**Comment by leedoopal** [comment]
@KoEonYack 
아~~~~ 그렇게 만드려면..
날짜에도 checkbox 또는 날짜 삭제 버튼이 있어야 할 것 같아요~~~

수정하는 과정에서 날짜를 삭제하고 싶을 때 -> 지금은 삭제할 수 있는 방법이 없거든요~~~

**Comment by KoEonYack** [comment]
@leedoopal 

맞아요~~~~~!! 그렇겠어요!! 추가해주시나요??🙌

**Comment by leedoopal** [comment]
@KoEonYack 
추가는 할 수 있는데 체크박스 UI 괜찮은가요??!
더 나은게 있으면 그걸로 아예 바꿔도 괜찮아보여요~~!

**Comment by KoEonYack** [comment]
@leedoopal 

그럼요~~~~~~~~~! 
선생님이 생각했을때 더 좋은거 있다면 해보아요!!

**Comment by leedoopal** [comment]
@KoEonYack 
오~~~~~ 고마워요!!

**Comment by leedoopal** [comment]
@KoEonYack 
선생님~~ 이벤트 수정 테스트 중인데 에러가나요! 왜그럴까요??

PUT admin/v2/events/74
// payload
```json
{"title":"null test 02","description":"수정테스트","organizer":"cindy","display_sequence":0,"event_link":"http","start_date_time":"2022-09-23T00:00","end_date_time":null,"tags":[{"id":11,"tag_name":"ㅎㅇㅎㅇ1","tag_color":"#667CF1"}],"cover_image_link":"","event_time_type":"DATE","use_start_date_time_yn":"N"}
```

// response error
```json
{"status_code":500,"status":"ERROR_500_00","message":"INTERNAL SERVER ERROR","errors":["Request processing failed; nested exception is java.lang.NullPointerException"]}
```

**Comment by KoEonYack** [comment]
@leedoopal 

오~ 함볼께요~~!

**Comment by leedoopal** [comment]
@KoEonYack 와 고마워요~~~~~~~

**Comment by KoEonYack** [comment]
@leedoopal 

선생님~~~ NULL 처리가 안되어는 부분이 있어서 수정했어요! 

배포전에 궁금한게 있는데요~!

GET admin/v2/events/74

```json
{
    "id": 74,
    "title": "null test 02",
    "description": "수정테스트",
    "organizer": "cindy",
    "event_link": "http",
    "cover_image_link": "",
    "display_sequence": 0,
    "event_time_type": "DATE",
    "start_day_week": "금",
    "use_start_date_time_yn": "N",
    "start_date_time": "2022-09-23T00:00",
    "end_day_week": null,
    "use_end_date_time_yn": null,
    "end_date_time": null,
    "create_date_time": "2022-09-23T23:03",
    "tags": [
        {
            "id": 11,
            "tag_name": "ㅎㅇㅎㅇ1",
            "tag_color": "#667CF1"
        }
    ]
}
```

이렇게 응답하면 선생님이 의도한게 맞을까요~?!

**Comment by leedoopal** [comment]
@KoEonYack 
와 로켓이에요 너무 고마워요~~~~~
넹넹 맞아요! 이상한 점이 있을까요???!

**Comment by KoEonYack** [comment]
@leedoopal 

아뇨~~~~~~

그러면 개발서버에 배포를 진행할께요~~~~~~~~~

**Comment by leedoopal** [comment]
@KoEonYack 

오 고마워요~~~~~~~~

**Comment by KoEonYack** [comment]
@leedoopal 

배포했어요~~~!!!!

**Comment by leedoopal** [comment]
@KoEonYack 고마워요~~~~!

@ohh31 관리자 dev에 배포했어요~~!! https://d-dev-event-client.vercel.app/admin/event

**Comment by leedoopal** [comment]
@KoEonYack dev에 배포하면 되는데 깜박하고 있었네요;; 오히려 늦은 것 같아서 미안해요

**Comment by KoEonYack** [comment]
@leedoopal 
오~~~~~~~ 아니에요~~!! 

![스크린샷 2022-09-27 오후 9 33 32](https://user-images.githubusercontent.com/28642484/192527409-57f30239-911e-405d-b323-89ff05aa6d31.png)

디자인이 바뀌었어요~~~~~!! 일자랑 시간이랑 거리가 멀어졌어요~~~~~~~~~!

**Comment by leedoopal** [comment]
@KoEonYack 
앗ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
<img width="719" alt="스크린샷 2022-09-27 오후 9 56 22" src="https://user-images.githubusercontent.com/39582981/192532359-583d907e-ce98-4476-b2c6-527988063e63.png">

제가 화면 분할로 보다보니 이렇게 나온다고 생각했는데 수정할게요!

**Comment by KoEonYack** [comment]
@leedoopal 

와~~~~~~~ 선생님의 의도가 아니었군요~~!!

--------------------------

이렇게 쓸 일은 없겠지만.. 

<img width="1108" alt="스크린샷 2022-09-27 오후 10 01 16" src="https://user-images.githubusercontent.com/28642484/192533392-c617a7e5-8c49-4dc9-99dd-4d64550190e6.png">

일자, 시간 아무것도 선택 안하고 행사 수정하면 기존에 저장된 값이 보이는데요!

이건.. 제 버그인것 같아서 함 볼께요....!

**Comment by leedoopal** [comment]
@KoEonYack 간격을 좁혀서 배포했어요~~~~~~!

---

앗 넹넹! 보고 프론트 이슈인 것 같으면 이야기해주어요!

**Comment by KoEonYack** [comment]
@leedoopal 
와~~~~~~~ 빨라요!! 고마워요!!

**Comment by leedoopal** [comment]
<img width="976" alt="스크린샷 2023-01-07 오전 12 01 27" src="https://user-images.githubusercontent.com/39582981/211038693-9ad127ec-fddd-4607-bff0-ce085109a8dd.png">

시작 시간은 있지만 종료 시간은 없는 경우인데, 종료 일자 뒤에 00:00 time이 붙는걸 제거하면 어떨까요??

**Comment by KoEonYack** [comment]
@leedoopal 
 
오~~~ 선생님 고마워요~~!! 행사 시간 노출 버그가 있어서 

> https://github.com/brave-people/Dev-Event-Web/issues/71 

여기에 선생님의 제안을 함께 넣을께요!!
