### ISSUE TITLE
[Bug] 시간 노출 버그 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#71]
@ohh31 

## 시간 미노출 Case 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/28642484/211039320-9dc3237d-17f1-45cd-8c38-2049bd758dcd.png">

<img width="599" alt="image" src="https://user-images.githubusercontent.com/28642484/211039330-5eb8220b-6133-4a6c-8e88-8c8f900cacc7.png">

------------------------------------------------

## 시간 존재하지 않는 행사에 대해서 시간 노출 Case  
<img width="606" alt="image" src="https://user-images.githubusercontent.com/28642484/211040155-69d333df-16b6-4810-a2c5-7c294f42d179.png">
> use_end_date_time_yn이 N인데 00:00 으로 노출되고 있는 상황! 
------------------------------------------------

위의 케이스에 대해서 행사 시간이 노출 안되고 있는데 확인 부탁할께~~~!!

**Comment by ohh31** [comment]
이슈 해결해서 배포했습니다 ! 감사합니다 :)
