### ISSUE TITLE
Google Analytics를 Production, Development 분리

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#74]
@ohh31 

앱 테스트 & 서버 버전 업그레이드 하면서 이래저래 로컬 & 개발 환경에서 테스트할때가 많은데 그럴때마다 구글 에넬러틱스에 찍혀서.

우리가 데이터로 판단하는데, 방문자수가 많지 않은 상태에서 테스트 방문지표가 계속 찍히는것은 맞지 않아 보이는 상황.

> https://velog.io/@leehyunho2001/Google-Analytics%EB%A5%BC-Production%EA%B3%BC-Development-%EC%97%90%EC%84%9C-%EB%94%B0%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0Next-Vercel

위의 방식대로 진행하면 좋을것같은데 검토하고 의견주면 좋겠어!

**Comment by ohh31** [comment]
넵 확인해서 수정해보겠습니다!!
