### ISSUE TITLE
링크 페이지 오류

### ISSUE THREAD

**Issue by HoJin9622** [brave-people/Dev-Event-Web#75]
2023년 5월 행사 링크가 맞지 않고 2개 단위로 밀리는 현상이 있습니다.

**Comment by jphan32** [comment]
이 버그가 원래부터 있던건가요?..

지금은 5개 단위로 밀리고 있네요 ^^;

![Uploading 스크린샷_2023-12-14_오전_4_05_22.png…](

**Comment by jphan32** [comment]
이 버그가 원래부터 있던건가요?..

지금은 5개 단위로 밀리고 있네요 ^^;

<img width="1069" alt="스크린샷_2023-12-14_오전_4_05_22" src="https://github.com/brave-people/Dev-Event-Web/assets/7111986/a662b87c-b2a5-4d80-8373-0ddd7106fdd7">

**Comment by jphan32** [comment]
첨부한 이미지처럼.. 같은 카드인데 URL이 다르게 잡혀있네요

<img width="1777" alt="스크린샷 2023-12-14 오전 4 22 22" src="https://github.com/brave-people/Dev-Event-Web/assets/7111986/e34045d5-24c1-4800-ac20-5d7215bbb380">

**Comment by KoEonYack** [comment]
@HoJin9622 , @jphan32 님~

이용해 주셔서 감사합니다^^

이슈를 정리하는김에 comment남깁니다. 

이것이.. 특정 조건에서 나타납니다. 

웹 페이지 개선 작업을 진행하고있어서 개선 작업이 완료되면 해당 문제도 같이 해결될 것으로 보입니다. 

감사합니다 (_ _)
