### ISSUE TITLE
[QA] Footer영역 오류 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#76]
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/0066a713-e9db-4f2e-bd83-d6fae7450714)
- (1): 문구 변경 2022 -> 2023
- (2): Github 아이콘 클릭시 https://github.com/brave-people/Dev-Event 로 이동해야함
- (3): 웨일 아이콘 깨져서 보임. 클릭시 https://store.whale.naver.com/detail/dfhagfnmecmkhdoeggeokfmmkbpiahek 로 이동해야함

**Comment by Resister-boy** [comment]
링크는 수정했습니다. 아래 웨일 이미지는 위에 토글 내려왔을 때 깨지는 것 같아요. 문제 찾아보겠습니다.

**Comment by KoEonYack** [comment]
수정 확인 완료~
