### ISSUE TITLE
[QA] 반응형 화면 > 다크모드 색상이 디자인과 다름 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#77]
## 현재 상황
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/6cb068bd-e4d5-4840-86b4-5e7dc55933ad)

## 기대 상황 
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/39744362-6327-4989-876a-5b7c96b73dcc)
- 반응형 화면에서 다크모드 전환 버튼이 디자인과 색상이 다름

**Comment by Resister-boy** [comment]
수정했습니다

**Comment by KoEonYack** [comment]
확인완료!
