### ISSUE TITLE
[QA] 상단 띠 > 닫기 클릭 > 새로고침시 다시 노출

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#78]
## 상황 
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/83c479df-e676-43e1-971b-53495065fb07)
상단 띠 > 닫기 클릭 > 새로고침시 다시 상단 띠 노출

## 논의
닫기 버튼 누르면 만료기간이 긴 쿠키에 저장하여 다시 노출하지 않도록 하는 것이 어떠한지

**Comment by samilulu** [comment]
좋습니다!

**Comment by KoEonYack** [comment]
@Resister-boy (X) 누르면 쿠키에 기록해서 페이지 다시 접근시 상단 띠가 다시 노출 되지 않도록 작업하면 됨!

**Comment by KoEonYack** [comment]
@Resister-boy 
이 부분 작업이 안되었네! x 표시 누르면 만료 기간이 3달짜리의 쿠기에다가 기록하면 될듯!

**Comment by KoEonYack** [comment]
@leedoopal 

아직 적용이 안되어있어서~ 해당건 작업해주면 됨!!

**Comment by KoEonYack** [comment]
작업 완료에 따른 이슈 종료
