### ISSUE TITLE
[QA] 2022년 1월 ~ 5월 검색 불필요

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#79]
![스크린샷 2023-07-26 오후 3 33 56](https://github.com/brave-people/Dev-Event-Web/assets/28642484/c505e325-5fa0-47ff-b35b-308514b1ab13)
- 데이터가 2022년 6월부터 있기에 1~5월은 클릭 불가능하게 하드코딩해도 괜찮음!

**Comment by Resister-boy** [comment]
수정했습니다

**Comment by KoEonYack** [comment]
확인 완료!
