### ISSUE TITLE
[QA] 행사 배너 이미지 모서리가 라운딩되어있지 않음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#80]
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/256979ce-6834-4ec0-abcd-78c35709eff0)
- 좌: 현재 코드 우: 피그마
- 행사 이미지의 끝 부분이 라운딩 처리되지 않았어!

**Comment by Resister-boy** [comment]
수정했씁니다!

**Comment by KoEonYack** [comment]
확인 완료!
