### ISSUE TITLE
[QA] 상단 띠가 다크모드 적용되지 않음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#81]
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/477a720e-ecf6-4387-9fbe-40cd2435e4e7)
- 상단 이미지: 디자인 
- 하단 이미지: 재훈의 코드
- 예상 결과: 디자인처럼 상단 띠에 다크모드 적용 필요

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
