### ISSUE TITLE
[QA] 태그 구분 띠가 위로 치우쳐있음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#82]
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/efd3d347-8a8b-4cc1-b96e-af7de48c580a)
- 상단 이미지: 디자인 이미지
- 하단 이미지: 재훈의 결과물
- 예상 결과: 상단에 치우친 태그 구분 선 `|` 이 중앙으로 와야함

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
