### ISSUE TITLE
[QA] 행사 시간 색상이 디자인과 상이함 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#83]
![image](https://github.com/brave-people/Dev-Event-Web/assets/28642484/2f2339e6-0f3b-4734-a3c4-29ce16f37429)
- 상단: 디자인
- 하단: 재훈의 코드
- 기대값: 디자인과 색상이 일치해야함

**Comment by Resister-boy** [comment]
수정했습니다

**Comment by KoEonYack** [comment]
확인완료!
