### ISSUE TITLE
[QA] 반응형 > 좌측에 여백이 없음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#84]
<img width="658" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/3eb2aa66-ab1d-4a77-a50a-e7f965a1499f">

- 좌측에 여백이 없는상태인데 옆에 여백을 주는게 어떤가요~ (가이드가 있어도 좋을듯!)

**Comment by Resister-boy** [comment]
수정했습니다

**Comment by KoEonYack** [comment]
확인 완료!
