### ISSUE TITLE
[QA] 공유하기 > 토스트 메시지가 디자인과 상이함 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#85]
<img width="500" alt="스크린샷 2023-07-26 오후 10 52 32" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/822ca53a-7b9b-4892-8bf6-e02e35e54f76">

> figma 토스트 메시지 

- @Resister-boy 너무 빨리 없어져서 캡쳐하지 못했는데 공유하기 토스트 메시지가 디자인과 다르네
- @samilulu 피그마의 토스트 메시지 디자인이 다크모드 / 라이트모드와 동하게 사용하는걸까~?

**Comment by Resister-boy** [comment]
수정했습니다

**Comment by samilulu** [comment]
아하 저희 다크모드 대응이 컬러만 다크세팅으로 전부 바꾸면 되는거라 토스트 메세지도 마찬가지에요!
라이트에서 배경이 light/Gray1 아이콘이 light/Primary 이런식이면 dark/Gray1, dark/Primary로 바뀌기만 하면 됩니다

**Comment by KoEonYack** [comment]
확인 완료!
