### ISSUE TITLE
[QA] 검색 결과 없음 > 피그마와 디자인 상이함

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#86]
<img width="614" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/403cdbb4-1227-4fee-8a32-d56234369b51">

- 상단: 피그마
- 하단: 재훈의 디자인
- @samilulu 추천 태그로 검색해 보세요에서 태그 노출 기준은 무엇이야~?

**Comment by samilulu** [comment]
저는 회원정보 딱히 연관 없이, 일괄로 대기업명 중에 랜덤 1개, 행사유형 중에 2개, 무료 행사 띄우는 걸로 생각했어요!
