### ISSUE TITLE
[QA] 종료된 행사 > 북마크 클릭시 소셜 로그인 버튼이 깨져서 보임 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#87]
<img width="1111" alt="스크린샷 2023-07-28 오후 6 14 42" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/06656d14-0bcc-4789-a70b-169f1370393d">

- 종료된 행사 > 북마크 클릭시 소셜 로그인 버튼이 깨져서 보임

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
