### ISSUE TITLE
[QA] 행사 이미지가 없는 경우 디폴트 이미지가 디자인과 상이함

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#88]
<img width="869" alt="스크린샷 2023-07-28 오후 6 18 21" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/7d762cab-6c1c-41c3-bb22-cd08b99fbb91">

<img width="260" alt="스크린샷 2023-07-28 오후 6 19 02" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/b21c8979-42b8-44e1-b5c7-37bb2244afed">

- 상단: 종료 행사일 경우 figma에 있는 이미지가 적용되어야함 
- 하단: 현재 적용된 디폴트 이미지

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
