### ISSUE TITLE
[QA] 종료 행사인 경우 행사 이미지가 상이함 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#89]
<img width="272" alt="스크린샷 2023-07-28 오후 6 20 32" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/42869ce8-5de0-4b23-aaed-869b0f70c68c">

<img width="567" alt="스크린샷 2023-07-28 오후 6 22 07" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/4abf6ad6-c0dc-4de1-8eb6-ead04181f0f8">

- 위: 현재 적용된 행사 이미지
- 아래: 디자인의 종료 행사 이미지

**Comment by Resister-boy** [comment]
수정했습니다

**Comment by KoEonYack** [comment]
확인 완료!
