### ISSUE TITLE
[QA] 마우스 호버링하면 행사 이미지가 각지게 보임 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#90]
<img width="265" alt="스크린샷 2023-07-28 오후 6 26 42" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/3c472280-b2d3-4152-8a56-d49dcf49b437">

- 캡처 이미지는 행사 이미지 위에 마우스 호버링했을때인데 호버링했을때 라운드 처리되어있던 행사 이미지가 각지게 변하는 상태야!

**Comment by Resister-boy** [comment]
마우스 호버링하면 이미지 스케일이 커지는 애니메이션을 적용했었는데, 그 부분을 제거했습니다.

**Comment by KoEonYack** [comment]
확인 완료!
