### ISSUE TITLE
[QA] 신규 행사일경우 행사 이미지위에 표시하는 블릿이 디자인과 상이함 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#91]
<img width="265" alt="스크린샷 2023-07-28 오후 6 32 44" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/e5416cdf-48cb-4bbd-a288-9fe8adef0756">
<img width="1274" alt="스크린샷 2023-07-28 오후 6 33 12" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/b11f7166-88dc-41ff-982a-ab24a2c31570">

- 신규 추가된 행사인 경우 아래의 이미지처럼 디자인 변경 필요함

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
