### ISSUE TITLE
[QA] 배너 크기가 다름 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#92]
<img width="1224" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/2e2ff5de-2870-4e39-80c4-13b529a2d0e7">

- 좌측: 현재 리얼에서의 배너 이미지
- 우측: 재훈의 결과물
- 개선사항
   - 기존과 뒷배경 이미자가 다른것 같음.

<img width="613" alt="image" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/85a01411-3777-48fd-b5d6-757df141f0b0">

- 그라 상하 위치는 동일해야함

**Comment by Resister-boy** [comment]
이미지는 같은 거 였는데, 이미지를 css에 background로 넣느냐, next/image 태그에 넣느냐에 따라 다르게 나온 거였습니다! 기존의 방식이 next/image였고 그렇게 수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
