### ISSUE TITLE
[QA] 2023년도가 표시됨으로 답답하게 보임 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#93]
<img width="1008" alt="스크린샷 2023-07-28 오후 7 07 19" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/58702a04-473c-4a19-81a8-ebb9a32e9349">

- 2023년이 행사 시작일, 종료일에 반복해서 등장하니 좀 답답해 보이는데~ 2023년을 아에 생략하는것은 어떨까!?

**Comment by KoEonYack** [comment]
- 직군: 색상 없는것
- 나머지: 색상있는것

**Comment by KoEonYack** [comment]
@Resister-boy 

![스크린샷 2023-08-03 오후 9 50 25](https://github.com/brave-people/Dev-Event-Web/assets/28642484/c4c04601-e4a3-48f6-9e9e-58d4cf2c601d)

시간은 이렇게 하면 됨!

**Comment by Resister-boy** [comment]
위에 포멧으로 날짜 나오도록 했습니다!
