### ISSUE TITLE
[QA] Today 뱃지가 노출되지 않음 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#94]
<img width="1317" alt="스크린샷 2023-07-28 오후 7 11 14" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/af6fca2e-d992-426b-8414-e66389127bb9">

<img width="1013" alt="스크린샷 2023-07-28 오후 7 11 26" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/c9d27620-68f0-4348-a97c-05610e9f783d">

- 행사 진행 기간에 오늘이 포함되어있으면 Today 뱃지가 노출되어야함. 오늘은 7월 28일이어서 Today 뱃지가 노출되어야하나 현재는 노출되지 않고있음

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
