### ISSUE TITLE
[QA] 행사 구분 선 조건과 색상이 다름 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Web#95]
<img width="1037" alt="스크린샷 2023-07-28 오후 11 30 11" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/c42de612-52f6-4738-bde8-6e02d9a17099">

> 상단: 재훈의 결과물

<br />
<br />
<br />
<br />

<img width="978" alt="스크린샷 2023-07-28 오후 11 29 23" src="https://github.com/brave-people/Dev-Event-Web/assets/28642484/501a13b5-b725-460a-94c4-43c3f1ca3d49">

> 하단: figma

- 재훈은 월 구분에 선을 넣었는데, figma을 보면 월 구분에는 선이 들어가 있지 않고, 행사 구분에만 선이 들어가있어.
- 선의 색상도 디자인과 차이가있네! (다크모드일때도 피그마랑 다름)

**Comment by Resister-boy** [comment]
수정했습니다!

**Comment by KoEonYack** [comment]
확인 완료!
